// Demo catalogue inserted on first launch (skip with SEED_DEMO=0).

const CATEGORIES = [
  { slug: 'phones', name: 'هواتف ذكية', name_fr: 'Smartphones' },
  { slug: 'audio', name: 'سماعات', name_fr: 'Audio' },
  { slug: 'chargers', name: 'شواحن وكوابل', name_fr: 'Chargeurs et câbles' },
  { slug: 'cases', name: 'أغلفة وحماية', name_fr: 'Coques et protection' },
  { slug: 'watches', name: 'ساعات ذكية', name_fr: 'Montres connectées' },
];

const PRODUCTS = [
  {
    slug: 'nova-x12',
    cat: 'phones',
    img: 'phone',
    price: 32900,
    compare_price: 36500,
    stock: 12,
    featured: 1,
    name: 'هاتف ذكي Nova X12 بذاكرة 128 جيغا',
    short_desc: 'شاشة 6.6 بوصة، بطارية 5000 ملي أمبير وكاميرا 50 ميغابكسل.',
    description: 'هاتف أنيق بأداء سريع للاستعمال اليومي، الألعاب الخفيفة والتصوير.\nيأتي في علبته الأصلية مع الشاحن وضمان 12 شهراً.',
    features: 'ذاكرة 128 جيغا + رام 6 جيغا\nشاشة 6.6 بوصة 90 هرتز\nبطارية 5000 ملي أمبير مع شحن سريع\nكاميرا خلفية 50 ميغابكسل\nضمان 12 شهراً',
    variants: 'أسود, أزرق, فضي',
    name_fr: 'Smartphone Nova X12 — 128 Go',
    short_desc_fr: 'Écran 6,6", batterie 5000 mAh et appareil photo 50 MP.',
    description_fr: 'Un téléphone élégant et rapide pour le quotidien, les jeux légers et la photo.\nLivré dans sa boîte d’origine avec chargeur et garantie 12 mois.',
    features_fr: 'Stockage 128 Go + 6 Go de RAM\nÉcran 6,6" 90 Hz\nBatterie 5000 mAh avec charge rapide\nCaméra arrière 50 MP\nGarantie 12 mois',
    variant_label_fr: 'Couleur',
    variants_fr: 'Noir, Bleu, Argent',
  },
  {
    slug: 'buds-pro',
    cat: 'audio',
    img: 'buds',
    price: 3900,
    compare_price: 5500,
    stock: 40,
    featured: 1,
    name: 'سماعات لاسلكية Buds Pro',
    short_desc: 'عزل للضوضاء، صوت نقي وبطارية تدوم حتى 24 ساعة مع العلبة.',
    description: 'سماعات بلوتوث 5.3 مريحة للأذن، مثالية للرياضة والمكالمات.\nاقتران تلقائي مع الهاتف بمجرد فتح العلبة.',
    features: 'بلوتوث 5.3 باتصال ثابت\nعزل نشط للضوضاء\n24 ساعة تشغيل مع العلبة\nمقاومة للعرق والرذاذ\nميكروفون مدمج للمكالمات',
    variants: 'أبيض, أسود',
    name_fr: 'Écouteurs sans fil Buds Pro',
    short_desc_fr: 'Réduction de bruit, son clair et jusqu’à 24 h d’autonomie avec le boîtier.',
    description_fr: 'Écouteurs Bluetooth 5.3 confortables, parfaits pour le sport et les appels.\nAppairage automatique dès l’ouverture du boîtier.',
    features_fr: 'Bluetooth 5.3 à connexion stable\nRéduction active du bruit\n24 h d’autonomie avec le boîtier\nRésistants à la sueur et aux éclaboussures\nMicro intégré pour les appels',
    variant_label_fr: 'Couleur',
    variants_fr: 'Blanc, Noir',
  },
  {
    slug: 'charger-25w',
    cat: 'chargers',
    img: 'charger',
    price: 2200,
    compare_price: 2900,
    stock: 60,
    featured: 1,
    name: 'شاحن سريع 25 واط مع كابل Type-C',
    short_desc: 'اشحن هاتفك من 0 إلى 50% في 30 دقيقة فقط.',
    description: 'شاحن جداري بتقنية الشحن السريع PD متوافق مع أغلب الهواتف الحديثة.\nيحمي البطارية من الحرارة الزائدة والشحن الزائد.',
    features: 'قدرة 25 واط PD\nكابل Type-C بطول 1 متر\nحماية من الحرارة والشحن الزائد\nمتوافق مع أغلب الهواتف',
    variants: '',
    name_fr: 'Chargeur rapide 25 W + câble USB-C',
    short_desc_fr: 'Chargez votre téléphone de 0 à 50 % en seulement 30 minutes.',
    description_fr: 'Chargeur secteur à charge rapide PD, compatible avec la plupart des téléphones récents.\nProtège la batterie contre la surchauffe et la surcharge.',
    features_fr: 'Puissance 25 W PD\nCâble USB-C de 1 mètre\nProtection contre la surchauffe et la surcharge\nCompatible avec la plupart des téléphones',
  },
  {
    slug: 'clear-case',
    cat: 'cases',
    img: 'case',
    price: 900,
    compare_price: 1300,
    stock: 100,
    featured: 0,
    name: 'غلاف حماية شفاف مضاد للصدمات',
    short_desc: 'حماية كاملة للزوايا مع الحفاظ على شكل هاتفك الأصلي.',
    description: 'غلاف سيليكون شفاف لا يصفرّ مع الوقت، بزوايا معززة ضد السقوط.\nاذكر موديل هاتفك في الملاحظات عند الطلب.',
    features: 'زوايا مقواة ضد الصدمات\nشفاف ولا يصفرّ\nحواف بارزة لحماية الكاميرا والشاشة\nخفيف ونحيف',
    variants: '',
    name_fr: 'Coque transparente antichoc',
    short_desc_fr: 'Protection complète des coins tout en gardant le look d’origine de votre téléphone.',
    description_fr: 'Coque en silicone transparente qui ne jaunit pas, avec coins renforcés contre les chutes.\nIndiquez le modèle de votre téléphone dans la note de commande.',
    features_fr: 'Coins renforcés antichoc\nTransparente, ne jaunit pas\nBords surélevés pour protéger caméra et écran\nFine et légère',
  },
  {
    slug: 'fit-watch-3',
    cat: 'watches',
    img: 'watch',
    price: 5900,
    compare_price: 7900,
    stock: 25,
    featured: 1,
    name: 'ساعة ذكية Fit Watch 3',
    short_desc: 'تتبع الخطوات، النبض والنوم مع إشعارات الهاتف على معصمك.',
    description: 'ساعة رياضية بشاشة ملونة واضحة تحت الشمس، وبطارية تدوم أسبوعاً كاملاً.\nمتوافقة مع أندرويد وآيفون.',
    features: 'شاشة 1.8 بوصة ملونة\nقياس نبض القلب والأكسجين\nإشعارات المكالمات والرسائل\nبطارية حتى 7 أيام\nمقاومة للماء IP67',
    variants: 'أسود, وردي, أخضر',
    name_fr: 'Montre connectée Fit Watch 3',
    short_desc_fr: 'Suivi des pas, du rythme cardiaque et du sommeil, avec vos notifications au poignet.',
    description_fr: 'Montre sport à écran couleur lisible en plein soleil, avec une semaine d’autonomie.\nCompatible Android et iPhone.',
    features_fr: 'Écran couleur 1,8"\nFréquence cardiaque et oxygène\nNotifications d’appels et de messages\nJusqu’à 7 jours d’autonomie\nÉtanche IP67',
    variant_label_fr: 'Couleur',
    variants_fr: 'Noir, Rose, Vert',
  },
  {
    slug: 'powerbank-20000',
    cat: 'chargers',
    img: 'powerbank',
    price: 4200,
    compare_price: null,
    stock: 30,
    featured: 0,
    name: 'باور بنك 20000 ملي أمبير',
    short_desc: 'اشحن هاتفك 4 مرات كاملة أينما كنت.',
    description: 'بطارية متنقلة بسعة كبيرة ومنفذين للشحن المتزامن، مع مؤشر رقمي للنسبة المتبقية.',
    features: 'سعة 20000 ملي أمبير\nمنفذ USB + منفذ Type-C\nشحن سريع 22.5 واط\nشاشة رقمية للنسبة',
    variants: '',
    name_fr: 'Batterie externe 20 000 mAh',
    short_desc_fr: 'Rechargez votre téléphone 4 fois, où que vous soyez.',
    description_fr: 'Batterie portable grande capacité avec deux ports de charge simultanée et un affichage numérique du niveau.',
    features_fr: 'Capacité 20 000 mAh\nPort USB + port USB-C\nCharge rapide 22,5 W\nAffichage numérique du niveau',
  },
];

const FR_FIELDS = ['name_fr', 'short_desc_fr', 'description_fr', 'features_fr', 'variant_label_fr', 'variants_fr'];

module.exports = { CATEGORIES, PRODUCTS, FR_FIELDS };
