// الولايات الجزائرية الـ58 مع أسعار توصيل افتراضية (تُعدَّل من لوحة التحكم).
// [الرمز, الاسم بالعربية, الاسم بالفرنسية, توصيل للمنزل, توصيل للمكتب]
const NORTH = [600, 400];
const HIGHLANDS = [700, 450];
const SOUTH = [900, 600];
const FAR_SOUTH = [1300, 900];

const WILAYAS = [
  [1, 'أدرار', 'Adrar', ...SOUTH],
  [2, 'الشلف', 'Chlef', ...NORTH],
  [3, 'الأغواط', 'Laghouat', ...HIGHLANDS],
  [4, 'أم البواقي', 'Oum El Bouaghi', ...NORTH],
  [5, 'باتنة', 'Batna', ...NORTH],
  [6, 'بجاية', 'Béjaïa', ...NORTH],
  [7, 'بسكرة', 'Biskra', ...HIGHLANDS],
  [8, 'بشار', 'Béchar', ...SOUTH],
  [9, 'البليدة', 'Blida', 500, 350],
  [10, 'البويرة', 'Bouira', ...NORTH],
  [11, 'تمنراست', 'Tamanrasset', ...FAR_SOUTH],
  [12, 'تبسة', 'Tébessa', ...NORTH],
  [13, 'تلمسان', 'Tlemcen', ...NORTH],
  [14, 'تيارت', 'Tiaret', ...NORTH],
  [15, 'تيزي وزو', 'Tizi Ouzou', ...NORTH],
  [16, 'الجزائر', 'Alger', 400, 250],
  [17, 'الجلفة', 'Djelfa', ...HIGHLANDS],
  [18, 'جيجل', 'Jijel', ...NORTH],
  [19, 'سطيف', 'Sétif', ...NORTH],
  [20, 'سعيدة', 'Saïda', ...NORTH],
  [21, 'سكيكدة', 'Skikda', ...NORTH],
  [22, 'سيدي بلعباس', 'Sidi Bel Abbès', ...NORTH],
  [23, 'عنابة', 'Annaba', ...NORTH],
  [24, 'قالمة', 'Guelma', ...NORTH],
  [25, 'قسنطينة', 'Constantine', ...NORTH],
  [26, 'المدية', 'Médéa', ...NORTH],
  [27, 'مستغانم', 'Mostaganem', ...NORTH],
  [28, 'المسيلة', "M'Sila", ...HIGHLANDS],
  [29, 'معسكر', 'Mascara', ...NORTH],
  [30, 'ورقلة', 'Ouargla', ...SOUTH],
  [31, 'وهران', 'Oran', ...NORTH],
  [32, 'البيض', 'El Bayadh', ...HIGHLANDS],
  [33, 'إليزي', 'Illizi', ...FAR_SOUTH],
  [34, 'برج بوعريريج', 'Bordj Bou Arréridj', ...NORTH],
  [35, 'بومرداس', 'Boumerdès', 500, 350],
  [36, 'الطارف', 'El Tarf', ...NORTH],
  [37, 'تندوف', 'Tindouf', ...FAR_SOUTH],
  [38, 'تيسمسيلت', 'Tissemsilt', ...NORTH],
  [39, 'الوادي', 'El Oued', ...SOUTH],
  [40, 'خنشلة', 'Khenchela', ...NORTH],
  [41, 'سوق أهراس', 'Souk Ahras', ...NORTH],
  [42, 'تيبازة', 'Tipaza', 500, 350],
  [43, 'ميلة', 'Mila', ...NORTH],
  [44, 'عين الدفلى', 'Aïn Defla', ...NORTH],
  [45, 'النعامة', 'Naâma', ...HIGHLANDS],
  [46, 'عين تموشنت', 'Aïn Témouchent', ...NORTH],
  [47, 'غرداية', 'Ghardaïa', ...SOUTH],
  [48, 'غليزان', 'Relizane', ...NORTH],
  [49, 'تيميمون', 'Timimoun', ...SOUTH],
  [50, 'برج باجي مختار', 'Bordj Badji Mokhtar', ...FAR_SOUTH],
  [51, 'أولاد جلال', 'Ouled Djellal', ...HIGHLANDS],
  [52, 'بني عباس', 'Béni Abbès', ...SOUTH],
  [53, 'عين صالح', 'In Salah', ...FAR_SOUTH],
  [54, 'عين قزام', 'In Guezzam', ...FAR_SOUTH],
  [55, 'تقرت', 'Touggourt', ...SOUTH],
  [56, 'جانت', 'Djanet', ...FAR_SOUTH],
  [57, 'المغير', "El M'Ghair", ...SOUTH],
  [58, 'المنيعة', 'El Meniaa', ...SOUTH],
];

module.exports = { WILAYAS };
